repo_url: https://github.com/Requisitos-de-Software/2025.2-Grupo03
repo_name: 2025.2-Grupo03
site_name: Grupo 03 - Requisitos de Software (2025.2)
site_url: https://requisitos-de-software.github.io/2025.2-Grupo03/

theme:
  name: material
  font:
    text: Roboto
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: pt

  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Dark mode
      primary: blue
      accent: light blue
      background: "#f5f7fa"
      text: "#22272e"
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Light mode
      primary: blue grey
      accent: cyan
      background: "#22272e"
      text: "#f5f7fa"

markdown_extensions:
  - attr_list
  - tables

nav:
  - Home: index.md
  - Atas: 
    - Ata 09/09/2025 1: Atas/ata09-09-2025_1.md
    - Ata 09/09/2025 2: Atas/ata09-09-2025_2.md
    - Ata 10/09/2025: Atas/ata10-09-2025.md
    - Ata 18/09/2025: Atas/ata18-09-2025.md
  - Apresentação: 
      - Introdução: Apresentação/apresentacao.md
      - Entrega 1: Apresentação/apresentacao1.md
      - Entrega 2: Apresentação/apresentacao2.md
      - Entrega 3: Apresentação/apresentacao3.md
      - Entrega 4: Apresentação/apresentacao4.md
      - Entrega 5: Apresentação/apresentacao5.md
      - Entrega 6: Apresentação/apresentacao6.md
      - Entrega Final: Apresentação/entrega_final.md
  - Planejamento: 
    - HeatMap: Planejamento/heatmap.md
    - Ferramentas: Planejamento/ferramentas.md
    - Cronograma planejado: Planejamento/cronograma_planejado.md
    - Cronograma executado: Planejamento/cronograma_executado.md
    - Aplicativos avaliados: Planejamento/Aplicativos.md
    - Aplicativo escolhido: Planejamento/aplicativo.md
  - Rich Picture: Rich-picture/richpicture.md
  - Verificação: 
    - Entrega 1: Verificacao/verificacao.md
    - Entrega 2: Verificacao/verificacao2.md
    - Entrega 3: Verificacao/verificacao3.md
    - Entrega 4: Verificacao/verificacao4.md
    - Entrega 6: Verificacao/verificacao6.md
  - Elicitação:
    - Perfil de Usuário: Elicitacao/perfil_usuario.md
    - Brainstorming - Perfil de Usuário: Elicitacao/brainstorming_perfil.md
    - Requisitos Elicitados: Elicitacao/requisitos_elicitados.md
    - Técnicas de Elicitação: 
      - Análise de Documentos: Elicitacao/analise_de_documentos.md
      - Entrevista: Elicitacao/entrevista.md
      - Brainstorming - Elicitação: Elicitacao/brainstorming.md
    - Técnicas de Priorização: 
      - First Thing First: Elicitacao/first_thing_first.md
      - Three Level Scale: Elicitacao/three_level_scale.md
      - $100: Elicitacao/100_dolares.md
      - MoSCoW: Elicitacao/moscow.md
  - Modelagem:
    - Metodologias Tradicionais:
      - Casos de Uso: Modelagem/casos_de_uso.md
      - Cenário: Modelagem/cenario.md
      - Especificação Suplementar: Modelagem/especificacao_suplementar.md
      - Léxico: Modelagem/lexico.md
    - Metodologias Ágeis:
      - Histórias de Usuário: Modelagem/historias_de_usuario.md
      - Backlog do Produto: Modelagem/backlog_do_produto.md
      - NFR Framework: Modelagem/nfr_framework.md
  - Pós Modelagem:
    - Matriz de Rastreabilidade: Pos-modelagem/matriz_de_rastreabilidade.md
    - Backward From: Pos-modelagem/backward.md
    - Forward From: Pos-modelagem/forward.md
  - Inspeção:
    - Grupo: 
      - Entrega 1: Inspeção/inspeção_grupo_1.md
      - Entrega 2: Inspeção/inspeção_grupo_2.md
      - Entrega 3: Inspeção/inspeção_grupo_3.md
      - Entrega 4: Inspeção/inspeção_grupo_4.md
      - Entrega 5: Inspeção/inspeção_grupo_5.md
      - Entrega 6: Inspeção/inspeção_grupo_6.md
    - Grupo +1: 
      - Entrega 1: Inspeção/inspeção_grupo_+1_1.md
      - Entrega 2: Inspeção/inspeção_grupo_+1_2.md
      - Entrega 3: Inspeção/inspeção_grupo_+1_3.md
      - Entrega 4: Inspeção/inspeção_grupo_+1_4.md
      - Entrega 5: 
        - Etapa 1: Inspeção/inspeção_Etapa1_grupo_+1_5.md
        - Etapa 2: Inspeção/inspeção_Etapa2_grupo_+1_5.md
        - Etapa 3: Inspeção/inspeção_Etapa3_grupo_+1_5.md
        - Etapa 4: Inspeção/inspeção_Etapa4_grupo_+1_5.md
        - Etapa 6: Inspeção/inspeção_Etapa6_grupo_+1_5.md
      - Entrega 6: Inspeção/inspeção_grupo_+1_6.md
  - Validação:
    - Prototipação: Validacao/prototipos.md
    - Comprovação Informal: Validacao/contato.md
  - Entrega Final:
    - Aplicativo Escolhido: Entrega_Final/aplicativo_escolhido.md
    - Artefatos Criados: Entrega_Final/artefatos_criados.md
    - Cronograma Final: Entrega_Final/cronograma_final.md
    - Execução do Projeto: Entrega_Final/execucao_projeto.md
    - Facilidades e Dificuldades: Entrega_Final/facilidades_dificuldades.md
    - Ferramentas: Entrega_Final/ferramentas.md
    - Resultados Alcançados: Entrega_Final/resultados_alcançados.md
    - Técnicas Utilizadas: Entrega_Final/tecnicas_utilizadas.md
    - Validação: Entrega_Final/validacao.md
    - Verificação: Entrega_Final/verificacao.md
